-- MySQL Script generated by MySQL Workbench
-- Fri Jan 13 17:48:17 2017
-- Model: analise    Version: 2.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema analise
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `analise` ;

-- -----------------------------------------------------
-- Schema analise
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `analise` DEFAULT CHARACTER SET latin1 COLLATE latin1_general_ci ;
USE `analise` ;

-- -----------------------------------------------------
-- Create user
-- -----------------------------------------------------
-- DROP USER `sisanalise`@`localhost`;
CREATE USER `sisanalise`@`localhost` identified by "123456";
GRANT ALL PRIVILEGES ON analise.* TO `sisanalise`@`localhost`;
FLUSH PRIVILEGES;

-- -----------------------------------------------------
-- Table `analise`.`pacientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `analise`.`pacientes` ;

CREATE TABLE IF NOT EXISTS `analise`.`pacientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `login` VARCHAR(20) NOT NULL,
  `senha` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `analise`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `analise`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `analise`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `login` VARCHAR(20) NOT NULL,
  `senha` VARCHAR(10) NOT NULL,
  `tipo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `analise`.`procedimentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `analise`.`procedimentos` ;

CREATE TABLE IF NOT EXISTS `analise`.`procedimentos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `preco` DECIMAL(10,2) NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_procedimentos_usuarios1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_procedimentos_usuarios1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `analise`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `analise`.`exames`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `analise`.`exames` ;

CREATE TABLE IF NOT EXISTS `analise`.`exames` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `paciente_id` INT NOT NULL,
  `procedimento_id` INT NOT NULL,
  `data` VARCHAR(10) NULL,
  INDEX `idx_exames_has_procedimentos` (`procedimento_id` ASC),
  INDEX `idx_exames_has_pacientes` (`paciente_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_exames_has_pacientes`
    FOREIGN KEY (`paciente_id`)
    REFERENCES `analise`.`pacientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_exames_has_procedimentos`
    FOREIGN KEY (`procedimento_id`)
    REFERENCES `analise`.`procedimentos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

--
-- Dumping data for table `usuarios`
--

INSERT INTO `usuarios` (`id`, `nome`, `login`, `senha`, `tipo`) VALUES(1, 'Administrador', 'admin', 'admin', 1);
INSERT INTO `usuarios` (`id`, `nome`, `login`, `senha`, `tipo`) VALUES(2, 'Operador', 'operador', 'operador', 2);

--
-- Dumping data for table `procedimentos`
--

INSERT INTO procedimentos (nome, preco, usuario_id) values ('GLICEMIA', '10', '1');
INSERT INTO procedimentos (nome, preco, usuario_id) values ('HIDROXIVITAMINA D', '15', '1');
INSERT INTO procedimentos (nome, preco, usuario_id) values ('PROTEINAS TOTAIS', '45', '1');
INSERT INTO procedimentos (nome, preco, usuario_id) values ('DENGUE', '22', '1');
INSERT INTO procedimentos (nome, preco, usuario_id) values ('BETA HCG QUANTITATIVO', '18', '1');
INSERT INTO procedimentos (nome, preco, usuario_id) values ('HEMOGRAMA', '12', '1');
INSERT INTO procedimentos (nome, preco, usuario_id) values ('VITAMINA K', '45', '1');
INSERT INTO procedimentos (nome, preco, usuario_id) values ('COLESTEROL TOTAL', '15', '1');
INSERT INTO procedimentos (nome, preco, usuario_id) values ('GRUPO SANGUINEO + FATOR RH', '10', '1');
INSERT INTO procedimentos (nome, preco, usuario_id) values ('HORMONIO DE CRESCIMENTO (GH)', '45', '1');

--
-- Dumping data for table `pacientes`
--

INSERT INTO `pacientes` (`id`, `nome`, `login`, `senha`) VALUES(1, 'Maria Silva', 'silva', '4620');
INSERT INTO `pacientes` (`id`, `nome`, `login`, `senha`) VALUES(2, 'José Santos', 'santos', '4298');
INSERT INTO `pacientes` (`id`, `nome`, `login`, `senha`) VALUES(3, 'Antônio Oliveira', 'oliveira', '4631');
INSERT INTO `pacientes` (`id`, `nome`, `login`, `senha`) VALUES(4, 'João Souza', 'souza', '3262');
INSERT INTO `pacientes` (`id`, `nome`, `login`, `senha`) VALUES(5, 'Francisco Pereira', 'pereira', '3415');
INSERT INTO `pacientes` (`id`, `nome`, `login`, `senha`) VALUES(6, 'Ana Costela', 'costela', '4291');
INSERT INTO `pacientes` (`id`, `nome`, `login`, `senha`) VALUES(7, 'Luiz Carvalho', 'carvalho', '4211');
INSERT INTO `pacientes` (`id`, `nome`, `login`, `senha`) VALUES(8, 'Paulo Almeida', 'almeida', '3181');
INSERT INTO `pacientes` (`id`, `nome`, `login`, `senha`) VALUES(9, 'Carlos Ferreira', 'ferreira', '4272');
INSERT INTO `pacientes` (`id`, `nome`, `login`, `senha`) VALUES(10, 'Manoel Ribeiro', 'ribeiro', '4817');
INSERT INTO `pacientes` (`id`, `nome`, `login`, `senha`) VALUES(11, 'Pedro Rodrigues', 'rodrigues', '4270');
INSERT INTO `pacientes` (`id`, `nome`, `login`, `senha`) VALUES(12, 'Francisca Gomes', 'gomes', '3898');
INSERT INTO `pacientes` (`id`, `nome`, `login`, `senha`) VALUES(13, 'Marcos Lima', 'lima', '3683');
INSERT INTO `pacientes` (`id`, `nome`, `login`, `senha`) VALUES(14, 'Raimundo Martins', 'martins', '3723');
INSERT INTO `pacientes` (`id`, `nome`, `login`, `senha`) VALUES(15, 'Sebastião Rocha', 'rocha', '4563');
INSERT INTO `pacientes` (`id`, `nome`, `login`, `senha`) VALUES(16, 'Antônia Alves', 'alves', '4649');
INSERT INTO `pacientes` (`id`, `nome`, `login`, `senha`) VALUES(17, 'Marcelo Araújo', 'araujo', '4557');
INSERT INTO `pacientes` (`id`, `nome`, `login`, `senha`) VALUES(18, 'Jorge Xavier', 'xavier', '3837');
INSERT INTO `pacientes` (`id`, `nome`, `login`, `senha`) VALUES(19, 'Márcia Barbosa', 'barbosa', '4516');
INSERT INTO `pacientes` (`id`, `nome`, `login`, `senha`) VALUES(20, 'Geraldo Castro', 'castro', '4069');
INSERT INTO `pacientes` (`id`, `nome`, `login`, `senha`) VALUES(21, 'Adriana Fernandes', 'fernandes', '3796');
INSERT INTO `pacientes` (`id`, `nome`, `login`, `senha`) VALUES(22, 'Sandra Melo', 'melo', '3773');
INSERT INTO `pacientes` (`id`, `nome`, `login`, `senha`) VALUES(23, 'Luis Azevedo', 'azevedo', '4477');
INSERT INTO `pacientes` (`id`, `nome`, `login`, `senha`) VALUES(24, 'Fernando Barros', 'barros', '4070');
INSERT INTO `pacientes` (`id`, `nome`, `login`, `senha`) VALUES(25, 'Fabio Cardoso', 'cardoso', '3916');
INSERT INTO `pacientes` (`id`, `nome`, `login`, `senha`) VALUES(26, 'Roberto Correia', 'correia', '4371');
INSERT INTO `pacientes` (`id`, `nome`, `login`, `senha`) VALUES(27, 'Márcio Cunha', 'cunha', '3109');
INSERT INTO `pacientes` (`id`, `nome`, `login`, `senha`) VALUES(28, 'Edson Dias', 'dias', '3431');
INSERT INTO `pacientes` (`id`, `nome`, `login`, `senha`) VALUES(29, 'André Mesquita', 'mesquita', '4828');

ALTER TABLE pacientes AUTO_INCREMENT = 30;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
