-- MySQL Script generated by MySQL Workbench
-- Tue Jan 31 17:07:25 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema provas
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `provas` ;

-- -----------------------------------------------------
-- Schema provas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `provas` DEFAULT CHARACTER SET latin1 ;
USE `provas` ;

-- DROP USER `sisprovas`@`localhost`;
CREATE USER `sisprovas`@`localhost` identified by "123456";
GRANT ALL PRIVILEGES ON provas.* TO `sisprovas`@`localhost`;
FLUSH PRIVILEGES;

-- -----------------------------------------------------
-- Table `provas`.`atletas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `provas`.`atletas` ;

CREATE TABLE IF NOT EXISTS `provas`.`atletas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `login` VARCHAR(20) NOT NULL,
  `senha` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `provas`.`eventos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `provas`.`eventos` ;

CREATE TABLE IF NOT EXISTS `provas`.`eventos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `preco` DECIMAL(10,2) NOT NULL,
  `data` VARCHAR(10) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `provas`.`registros`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `provas`.`registros` ;

CREATE TABLE IF NOT EXISTS `provas`.`registros` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `atleta_id` INT NOT NULL,
  `evento_id` INT NOT NULL,
  `data` VARCHAR(10) NULL,
  `pago` BIT(1) NOT NULL DEFAULT 0,
  INDEX `idx_registros_has_eventos` (`evento_id` ASC),
  INDEX `idx_registros_has_atletas` (`atleta_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_registros_has_atletas`
    FOREIGN KEY (`atleta_id`)
    REFERENCES `provas`.`atletas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_registros_has_eventos`
    FOREIGN KEY (`evento_id`)
    REFERENCES `provas`.`eventos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

--
-- Dumping data for table `atletas`
--

INSERT INTO `atletas` (`id`, `nome`, `login`, `senha`) VALUES(1, 'Maria Silva', 'silva', '4620');
INSERT INTO `atletas` (`id`, `nome`, `login`, `senha`) VALUES(2, 'José Santos', 'santos', '4298');
INSERT INTO `atletas` (`id`, `nome`, `login`, `senha`) VALUES(3, 'Antônio Oliveira', 'oliveira', '4631');
INSERT INTO `atletas` (`id`, `nome`, `login`, `senha`) VALUES(4, 'João Souza', 'souza', '3262');
INSERT INTO `atletas` (`id`, `nome`, `login`, `senha`) VALUES(5, 'Francisco Pereira', 'pereira', '3415');
INSERT INTO `atletas` (`id`, `nome`, `login`, `senha`) VALUES(6, 'Ana Costela', 'costela', '4291');
INSERT INTO `atletas` (`id`, `nome`, `login`, `senha`) VALUES(7, 'Luiz Carvalho', 'carvalho', '4211');
INSERT INTO `atletas` (`id`, `nome`, `login`, `senha`) VALUES(8, 'Paulo Almeida', 'almeida', '3181');
INSERT INTO `atletas` (`id`, `nome`, `login`, `senha`) VALUES(9, 'Carlos Ferreira', 'ferreira', '4272');
INSERT INTO `atletas` (`id`, `nome`, `login`, `senha`) VALUES(10, 'Manoel Ribeiro', 'ribeiro', '4817');
INSERT INTO `atletas` (`id`, `nome`, `login`, `senha`) VALUES(11, 'Pedro Rodrigues', 'rodrigues', '4270');
INSERT INTO `atletas` (`id`, `nome`, `login`, `senha`) VALUES(12, 'Francisca Gomes', 'gomes', '3898');
INSERT INTO `atletas` (`id`, `nome`, `login`, `senha`) VALUES(13, 'Marcos Lima', 'lima', '3683');
INSERT INTO `atletas` (`id`, `nome`, `login`, `senha`) VALUES(14, 'Raimundo Martins', 'martins', '3723');
INSERT INTO `atletas` (`id`, `nome`, `login`, `senha`) VALUES(15, 'Sebastião Rocha', 'rocha', '4563');
INSERT INTO `atletas` (`id`, `nome`, `login`, `senha`) VALUES(16, 'Antônia Alves', 'alves', '4649');
INSERT INTO `atletas` (`id`, `nome`, `login`, `senha`) VALUES(17, 'Marcelo Araújo', 'araujo', '4557');
INSERT INTO `atletas` (`id`, `nome`, `login`, `senha`) VALUES(18, 'Jorge Xavier', 'xavier', '3837');
INSERT INTO `atletas` (`id`, `nome`, `login`, `senha`) VALUES(19, 'Márcia Barbosa', 'barbosa', '4516');
INSERT INTO `atletas` (`id`, `nome`, `login`, `senha`) VALUES(20, 'Geraldo Castro', 'castro', '4069');
INSERT INTO `atletas` (`id`, `nome`, `login`, `senha`) VALUES(21, 'Adriana Fernandes', 'fernandes', '3796');
INSERT INTO `atletas` (`id`, `nome`, `login`, `senha`) VALUES(22, 'Sandra Melo', 'melo', '3773');
INSERT INTO `atletas` (`id`, `nome`, `login`, `senha`) VALUES(23, 'Luis Azevedo', 'azevedo', '4477');
INSERT INTO `atletas` (`id`, `nome`, `login`, `senha`) VALUES(24, 'Fernando Barros', 'barros', '4070');
INSERT INTO `atletas` (`id`, `nome`, `login`, `senha`) VALUES(25, 'Fabio Cardoso', 'cardoso', '3916');
INSERT INTO `atletas` (`id`, `nome`, `login`, `senha`) VALUES(26, 'Roberto Correia', 'correia', '4371');
INSERT INTO `atletas` (`id`, `nome`, `login`, `senha`) VALUES(27, 'Márcio Cunha', 'cunha', '3109');
INSERT INTO `atletas` (`id`, `nome`, `login`, `senha`) VALUES(28, 'Edson Dias', 'dias', '3431');
INSERT INTO `atletas` (`id`, `nome`, `login`, `senha`) VALUES(29, 'André Mesquita', 'mesquita', '4828');

ALTER TABLE atletas AUTO_INCREMENT = 30;

--
-- Dumping data for table `eventos`
--

INSERT INTO eventos (nome, preco, data) values ('COPA 2017 MOUNTAIN BIKE', '120', '2017-05-21');
INSERT INTO eventos (nome, preco, data) values ('BIKE ENDURO DE MARIANA', '75', '2017-04-09');
INSERT INTO eventos (nome, preco, data) values ('IRON BIKER BRASIL 2017', '400', '2017-09-16');
INSERT INTO eventos (nome, preco, data) values ('TROFEU REI DA MONTANHA', '80', '2017-06-04');
INSERT INTO eventos (nome, preco, data) values ('MARATONA INTERNACIONAL ESTRADA REAL', '150', '2017-04-23');
INSERT INTO eventos (nome, preco, data) values ('20o. PEDAL DAS LULUZINHAS', '10', '2017-02-10');
INSERT INTO eventos (nome, preco, data) values ('GOLDEN BIKER 2017', '180', '2017-05-20');
INSERT INTO eventos (nome, preco, data) values ('CIMTB - COPA INTERNACIONAL DE MTB', '200', '2017-08-20'); 
INSERT INTO eventos (nome, preco, data) values ('DESAFIO MINEIRO DE MARATONA 2017', '120', '2017-07-09');
INSERT INTO eventos (nome, preco, data) values ('XTERRA CAMP OURO PRETO 2017', '170', '2017-07-22');

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
